server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario
          uri: http://localhost:8001
          predicates:
            - Path=/api/usuario/**
        - id: carro
          uri: http://localhost:8002
          predicates:
            - Path=/api/carro/**
        - id: moto
          uri: http://localhost:8003
          predicates:
            - Path=/api/moto/**